services:
  # Frontend service
  - type: web
    name: speed-opt-tool-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend service
  - type: web
    name: speed-opt-tool-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node api-proxy.js
    envVars:
      - key: NODE_ENV
        value: production 